DROP TABLE GENRES;
CREATE TABLE GENRES(
GENRES_ID NUMBER PRIMARY KEY, /*장르 ID*/
GENRES_NAME VARCHAR2(30) /*장르 이름*/
);

INSERT INTO GENRES VALUES(12,'모험');
INSERT INTO GENRES VALUES(28,'액션');
INSERT INTO GENRES VALUES(16,'애니메이션');
INSERT INTO GENRES VALUES(35,'코미디');
INSERT INTO GENRES VALUES(80,'범죄');
INSERT INTO GENRES VALUES(99,'다큐멘터리');
INSERT INTO GENRES VALUES(18,'드라마');
INSERT INTO GENRES VALUES(10751,'가족');
INSERT INTO GENRES VALUES(14,'판타지');
INSERT INTO GENRES VALUES(36,'역사');
INSERT INTO GENRES VALUES(27,'공포');
INSERT INTO GENRES VALUES(10402,'음악');
INSERT INTO GENRES VALUES(9648,'미스터리');
INSERT INTO GENRES VALUES(10749,'로맨스');
INSERT INTO GENRES VALUES(878,'SF');
INSERT INTO GENRES VALUES(10770,'TV 영화');
INSERT INTO GENRES VALUES(53,'스릴러');
INSERT INTO GENRES VALUES(10752,'전쟁');
INSERT INTO GENRES VALUES(37,'서부');			
					