DROP TABLE NOTICE;

CREATE TABLE NOTICE(
NOTICE_ID NUMBER PRIMARY KEY,
NOTICE_NAME VARCHAR2(40) REFERENCES  USERS (USER_ID),
NOTICE_SUBJECT VARCHAR2(100),
NOTICE_CONTENT VARCHAR2(300),
NOTICE_DATE DATE
);	

