DROP TABLE RATING_STAR;

CREATE TABLE RATING_STAR(
RATING_STAR_number NUMBER PRIMARY KEY,
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID),
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
RATING_STAR_value NUMBER CHECK (RATING_STAR_value IN(1,2,3,4,5))
);




INSERT INTO RATING_STAR VALUES((select nvl(max(RATING_STAR_number),0) from RATING_STAR)+1,
330457,'duswl13',4);

INSERT INTO RATING_STAR VALUES((select nvl(max(RATING_STAR_number),0) from RATING_STAR)+1,
330457,'sonyeonsoo',5);

INSERT INTO RATING_STAR VALUES((select nvl(max(RATING_STAR_number),0) from RATING_STAR)+1,
330457,'jiyeon',2);

