DROP TABLE RATING_STAR;

CREATE TABLE RATING_STAR(
RATING_STAR_number NUMBER PRIMARY KEY,
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID),
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
RATING_STAR_value NUMBER CHECK (RATING_STAR_value IN(1,2,3,4,5))
);