DROP TABLE RATING_FACE;

CREATE TABLE RATING_FACE(
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID), /*��ȭ ID*/
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID), /*���� ID*/
RATING_FACE_value NUMBER CHECK (RATING_FACE_value IN(1,2)),
RATING_FACE_DATE DATE,
/*1 : ���ƿ�  2:�Ⱦ��*/
 CONSTRAINT RATING_FACE_primarykey PRIMARY KEY (MOVIE_ID, USER_ID)
);


INSERT INTO RATING_FACE VALUES(330457,'duswl13',1,sysdate);
INSERT INTO RATING_FACE VALUES(330457,'sonyeonsoo',1,sysdate);
INSERT INTO RATING_FACE VALUES(330457,'jiyeon',2,sysdate);

INSERT INTO RATING_FACE VALUES(429617,'duswl13',2,sysdate);
INSERT INTO RATING_FACE VALUES(429617,'sonyeonsoo',1,sysdate);
/**DELETE FROM RATING_FACE WHERE MOVIE_ID=330457 AND USER_ID='duswl13';
**/


/*내가 좋아요 표정점수를 누른 영화 목록*/
SELECT MOVIE_ID FROM RATING_FACE WHERE USER_ID = 'duswl13' AND RATING_FACE_VALUE = 1;

/*내 좋아요 영화들의 다른 유저들의 1 평가들*/
SELECT * FROM RATING_FACE WHERE MOVIE_ID IN (SELECT MOVIE_ID 
											FROM RATING_FACE WHERE USER_ID = 'duswl13'
											AND RATING_FACE_VALUE = 1)
						AND USER_ID!='duswl13' and RATING_FACE_VALUE = 	1;	
						
						
/*이 결과를 같은 USER_ID로 그룹을 지어서 COUNT*/
SELECT COUNT(*),USER_ID FROM RATING_FACE WHERE MOVIE_ID IN (SELECT MOVIE_ID 
											FROM RATING_FACE WHERE USER_ID = 'duswl13'
											AND RATING_FACE_VALUE = 1) 
						AND USER_ID!='duswl13' AND RATING_FACE_VALUE = 1
						GROUP BY USER_ID
						ORDER BY COUNT(*) DESC;

/*상위 2명을 골라 그 유저의 영화목록을 가져옴*/
SELECT * FROM RATING_FACE WHERE RATING_FACE_VALUE = 1 AND USER_ID IN
(SELECT USER_ID FROM (
SELECT COUNT(*) C,USER_ID FROM RATING_FACE WHERE MOVIE_ID IN (SELECT MOVIE_ID 
											FROM RATING_FACE WHERE USER_ID = 'duswl13'
											AND RATING_FACE_VALUE = 1) 
						AND USER_ID!='duswl13' AND RATING_FACE_VALUE = 1
						GROUP BY USER_ID
						ORDER BY C DESC)
					WHERE ROWNUM < 3);
					
/*그 영화 목록 중 내가 본(표정점수 등록한) 영화는 제외*/
SELECT MOVIE_ID FROM RATING_FACE WHERE RATING_FACE_VALUE = 1 AND USER_ID IN
(SELECT USER_ID FROM (
SELECT COUNT(*) C,USER_ID FROM RATING_FACE WHERE MOVIE_ID IN (SELECT MOVIE_ID 
											FROM RATING_FACE WHERE USER_ID = 'duswl13'
											AND RATING_FACE_VALUE = 1) 
						AND USER_ID!='duswl13' AND RATING_FACE_VALUE = 1
						GROUP BY USER_ID
						ORDER BY C DESC)
					WHERE ROWNUM  < 3) AND MOVIE_ID NOT IN 
					(SELECT MOVIE_ID FROM RATING_FACE WHERE USER_ID = 'duswl13');
							
					
/*그 영화에 대한 정보*/
SELECT * FROM MOVIE WHERE MOVIE_ID IN (
SELECT MOVIE_ID FROM RATING_FACE WHERE RATING_FACE_VALUE = 1 AND USER_ID IN
(SELECT USER_ID FROM (
SELECT COUNT(*) C,USER_ID FROM RATING_FACE WHERE MOVIE_ID IN (SELECT MOVIE_ID 
											FROM RATING_FACE WHERE USER_ID = 'duswl13'
											AND RATING_FACE_VALUE = 1) 
						AND USER_ID!='duswl13' AND RATING_FACE_VALUE = 1
						GROUP BY USER_ID
						ORDER BY C DESC)
					WHERE ROWNUM  < 3) AND MOVIE_ID NOT IN 
					(SELECT MOVIE_ID FROM RATING_FACE WHERE USER_ID = 'duswl13'));
							
										

