DROP TABLE RATING_FACE;

CREATE TABLE RATING_FACE(
RATING_FACE_NUMBER NUMBER PRIMARY KEY,
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID),
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
RATING_STAR_value NUMBER CHECK (RATING_STAR_value IN(1,2,3,4,5))
);