DROP TABLE review;

CREATE TABLE review(
REVIEW_NUMBER NUMBER PRIMARY KEY,
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID),
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
REVIEW_TITLE VARCHAR2(100),
REVIEW_CONTENT VARCHAR2(1000),
REVIEW_DATE DATE
);