DROP TABLE REVIEW_LIKE;

CREATE TABLE REVIEW_LIKE(
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID),
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
LIKE_ID VARCHAR2(40) REFERENCES USERS (USER_ID)
);


INSERT INTO REVIEW_LIKE VALUES(330457,'duswl13','sonyeonsoo');
INSERT INTO REVIEW_LIKE VALUES(330457,'duswl13','jiyeon');

INSERT INTO REVIEW_LIKE VALUES(330457,'sonyeonsoo','duswl13');
INSERT INTO REVIEW_LIKE VALUES(330457,'sonyeonsoo','sonyeonsoo');
INSERT INTO REVIEW_LIKE VALUES(330457,'sonyeonsoo','jiyeon');

INSERT INTO REVIEW_LIKE VALUES(330457,'jiyeon','jiyeon');


/*리뷰 좋아요 목록*/
SELECT USER_ID, (SELECT COUNT(*) FROM
				REVIEW_LIKE 
				WHERE REVIEW_LIKE.USER_ID = REVIEW.USER_ID)
FROM REVIEW WHERE MOVIE_ID= 330457;

