DROP TABLE USER_HIDDEN_MOVIE;

CREATE TABLE USER_HIDDEN_MOVIE(
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID),
CONSTRAINT USER_HIDDEN_MOVIE_primarykey PRIMARY KEY (USER_ID, MOVIE_ID)
);

select * from USER_HIDDEN_MOVIE where user_id='duswl13';

INSERT INTO USER_HIDDEN_MOVIE VALUES(
'duswl13',475557);
INSERT INTO USER_HIDDEN_MOVIE VALUES(
'duswl13',330457);

INSERT INTO USER_HIDDEN_MOVIE VALUES(
'sonyeonsoo',474350);

INSERT INTO USER_HIDDEN_MOVIE VALUES(
'jiyeon',399579);
