DROP TABLE USER_HIDDEN_MOVIE;

CREATE TABLE USER_HIDDEN_MOVIE(
USER_HIDDEN_MOVIE_NUMBER NUMBER PRIMARY KEY,
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
MOVIE_ID NUMBER REFERENCES MOVIE (MOVIE_ID)
);

INSERT INTO USER_HIDDEN_MOVIE VALUES((select nvl(max(USER_HIDDEN_MOVIE_NUMBER),0) from USER_HIDDEN_MOVIE)+1,
'duswl13',475557);

INSERT INTO USER_HIDDEN_MOVIE VALUES((select nvl(max(USER_HIDDEN_MOVIE_NUMBER),0) from USER_HIDDEN_MOVIE)+1,
'sonyeonsoo',474350);

INSERT INTO USER_HIDDEN_MOVIE VALUES((select nvl(max(USER_HIDDEN_MOVIE_NUMBER),0) from USER_HIDDEN_MOVIE)+1,
'jiyeon',399579);
