DROP TABLE USER_GENRES;

CREATE TABLE USER_GENRES(
GENRES_ID NUMBER REFERENCES GENRES (GENRES_ID),
USER_ID VARCHAR2(40) REFERENCES USERS (USER_ID),
 CONSTRAINT USER_GENRES_primarykey PRIMARY KEY (GENRES_ID, USER_ID)
);

select * from USER_GENRES where USER_ID = 'duswl13';
delete from USER_GENRES where USER_ID='duswl13' and GENRES_ID=14;

INSERT INTO USER_GENRES VALUES(
16,'duswl13');
INSERT INTO USER_GENRES VALUES(
14,'duswl13');
INSERT INTO USER_GENRES VALUES(
10749,'duswl13');


INSERT INTO USER_GENRES VALUES(
10749,'sonyeonsoo');
INSERT INTO USER_GENRES VALUES(
36,'sonyeonsoo');
INSERT INTO USER_GENRES VALUES(
10402,'sonyeonsoo');
INSERT INTO USER_GENRES VALUES(
35,'sonyeonsoo');


INSERT INTO USER_GENRES VALUES(
28,'jiyeon');
INSERT INTO USER_GENRES VALUES(
35,'jiyeon');
INSERT INTO USER_GENRES VALUES(
10751,'jiyeon');
INSERT INTO USER_GENRES VALUES(
27,'jiyeon');
INSERT INTO USER_GENRES VALUES(
9648,'jiyeon');


INSERT ALL
INTO USER_GENRES VALUES(35,'admin1')
INTO USER_GENRES VALUES(27,'admin1')
SELECT * FROM DUAL;



select * from USER_GENRES;
/*유저의 관심 목록 가져오기*/
/*select * from USER_GENRES where USER_ID = 'duswl13';*/